### PR TITLE
Clamp bugfix

### LINKED ISSUE #2362: clamping to or from 0 seems broken
We have this for the ascend cluster and given the steps below 

```yaml
form:
  - gpus
  - node_type
attributes:
  gpus:
    widget: number_field
    value: 0
    min: 0
    max: 4
  node_type:
    widget: select
    label: "Node type"
    help: |
      Need docs
    options:
      - [ 
          "cpu", "any",
          data-min-num-cores: 1,
          data-min-gpus: 0,
          data-max-gpus: 0,
          data-max-num-cores: 84,
          data-hide-gpus: true,
        ]
      - [ 
          "gpu", "gpu-any",
          data-min-gpus: 1,
          data-max-gpus: 4,
          data-min-num-cores: 1,
          data-max-num-cores: 88,
        ]
```

steps to reproduce:
* set the node_type to gpus
* set gpus to 0
* select node type cpu
* select node type gpu
* [bug] see that gpus is now set to 4 when it should have been set to 0.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203325968198874) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1202821104799596/1203325968198874

### PR DESCRIPTION
**Pull request by johrstrom**
Fixes #2362 which ended up being a few bugs. I'll leave comments for rationale for changes in the files.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203338277276811) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1135148780858012/1203338277276811

### CODE REVIEW

File: apps/dashboard/app/javascript/packs/batch_connect.js [hunk 1]
```diff
@@ -423,16 +424,16 @@ function clamp(currentValue, previous, next) {
     return undefined;
 
   // you've set the boundary, so when you go to the next value - keep it at the next's boundary
-  } else if(previous && previous['max'] && currentValue == previous['max']) {
-    return next['max'];
-  } else if(previous && previous['min'] && currentValue == previous['min']) {
+  } else if(currentValue === previous['min']) {
```
Comment (johrstrom) [inline apps/dashboard/app/javascript/packs/batch_connect.js:427]: `previous['max']` can be 0 which evaluates to fasley - so just stop checking for it's existance because javascript deals well with comparing `undefined` or `null` against actual objects.

This also makes sure we check the minimum before the maximum so things get clamped to the minimums.

File: apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml [hunk 2]
```diff
@@ -57,37 +61,52 @@ attributes:
...
-          data-max-bc-num-slots: 200,
-          data-min-bc-num-hours: 444,
-          data-max-bc-num-hours: 555,
+          # note that all these values are strings
+          data-hide-cuda-version: "true",
+          data-hide-advanced-options: "true",
+          data-min-bc-num-slots: "100",
+          data-max-bc-num-slots: "200",
+          data-min-bc-num-hours: "444",
+          data-max-bc-num-hours: "555",
```
Comment (johrstrom) [inline apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml:97]: These modifications on old tests are just to be sure that when folks use strings instead of integers or booleans everything still works as expected.

**Review by Oglopf — APPROVED** [review]
Looks good.
