### PR TITLE
Fix false values 4521

### LINKED ISSUE #4521: Unify different FALSE_VALUES implementations
A quick search of the repository shows 5 different definitions of the FALSE_VALUES array used for interpreting environment variables and configuration settings, and they are not always consistent. For example in `dashboard/app/models/configuration_property.rb`, we have `FALSE_VALUES = ['', '0', 'F', 'FALSE', 'OFF', 'NO'].freeze` and in `apps/dashboard/config/configuration_singleton.rb` we have `FALSE_VALUES = [nil, false, '', 0, '0', 'f', 'F', 'false', 'FALSE', 'off', 'OFF', 'no', 'NO'].freeze`. The capitalization differences could certainly cause problems at some point, and a single FALSE_VALUES would be easier to maintain and document around. Four of the implementations are in the dashboard, and only one is in myjobs, so even consolidating them within each app would certainly clear up a lot, but making a universal ondemand constant class/file would probably straighten it out best, especially since FALSE_VALUES likely isn't the only constant we have duplicated in multiple locations.

### PR DESCRIPTION
**Pull request by Bubballoo3**
Fixes #4521 by adding the BoolReader module and using this whenever we need to cast a user-supplied string (such as those in config files) into a boolean. Passes all tests

### CODE REVIEW

File: apps/dashboard/config/configuration_singleton.rb [hunk 1]
```diff
@@ -20,6 +20,8 @@
 # ConfigurationSingleton and defining it as a class method on Configuration.
 #
 class ConfigurationSingleton
+  require_relative '../app/models/concerns/bool_reader.rb'
```
Comment (johrstrom) [inline apps/dashboard/config/configuration_singleton.rb]: This is a bit of a nit-pick, but can we move this up to the other requires? I think I just want uniformity here.

File: apps/dashboard/app/models/configuration_property.rb [hunk 2]
```diff
@@ -15,7 +14,7 @@ def self.property(name:, default_value: nil, read_from_env: false, env_names: ni
   end
 
   attr_reader :name, :default_value, :read_from_environment, :environment_names
-  alias_method :read_from_environment?, :read_from_environment
+  alias read_from_environment? read_from_environment
```
Comment (johrstrom) [inline apps/dashboard/app/models/configuration_property.rb:17]: Why make this change here? Is it a linting thing? I'd have to pull this down to see what a linter would say.

Comment (Bubballoo3) [reply apps/dashboard/app/models/configuration_property.rb:17]: Yeah that was a rubocop suggestion, I can grab a screenshot for you real quick

Comment (Bubballoo3) [reply apps/dashboard/app/models/configuration_property.rb:17]: image

Comment (Bubballoo3) [reply apps/dashboard/app/models/configuration_property.rb:17]: Should I try to make linting suggestions that come up in code I am working on? Or do we have the bot go through and autocorrect stuff in a dedicated PR?

Comment (Bubballoo3) [reply apps/dashboard/app/models/configuration_property.rb:17]: And then after you autocorrect alias_method to alias, it wants to take the colon off of `:read_from_environment`

image

Comment (johrstrom) [reply apps/dashboard/app/models/configuration_property.rb:17]: OK, works for me then.
