### PR TITLE
default to allow no hosts

### LINKED ISSUE #2566: allowed_hosts not being populated
#2559 seems to have broken this functionality. `ALLOWED_HOSTS` is not being populated.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203960321892730) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by johrstrom**
allowed hosts still doesn't work.  This actually fixes #2566 and I confirmed in containers. Both with a prehook set and without one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203960902381432) by [Unito](https://www.unito.io)

### CODE REVIEW

File: nginx_stage/lib/nginx_stage.rb [hunk 1]
```diff
@@ -145,6 +145,8 @@ def self.clean_nginx_env(user:)
       "RAILS_LOG_TO_STDOUT" => "true",
       # name change here because only OOD_* from apache is allowed through sudo rules
       "ALLOWED_HOSTS" => ENV['OOD_ALLOWED_HOSTS'],
+      # set the duplicate to keep clean_nginx_env impepodent
+      "OOD_ALLOWED_HOSTS" => ENV['OOD_ALLOWED_HOSTS'],
```
Comment (johrstrom) [inline nginx_stage/lib/nginx_stage.rb:149]: One issue we were seeing was this function `clean_nginx_env` being called 2 or more times. First time, `ALLOWED_HOSTS` and `OOD_ALLOWED_HOSTS` erased. So, the next time it ran it then erased `ALLOWED_HOSTS` because `OOD_ALLOWED_HOSTS` was unset.

File: mod_ood_proxy/lib/ood/nginx_stage.lua [hunk 2]
```diff
@@ -15,7 +15,8 @@ function pun(r, bin, user, app_init_url, exports, pre_hook_root_cmd, allowed_hos
   if pre_hook_root_cmd then
     local env_table = exports_to_table(r, exports)
     if allowed_hosts then
-      env_table["OOD_ALLOWED_HOSTS"] = allowed_hosts
+      -- capture2e_with_env will prefix OOD_
+      env_table["ALLOWED_HOSTS"] = allowed_hosts
```
Comment (johrstrom) [inline mod_ood_proxy/lib/ood/nginx_stage.lua:19]: This behavior of `capture2e_with_env` prefixing isn't immediately apparent so left the comment for the same.

**Review by treydock — APPROVED** [review]

File: nginx_stage/lib/nginx_stage.rb [hunk 3]
```diff
@@ -145,6 +145,8 @@ def self.clean_nginx_env(user:)
       "RAILS_LOG_TO_STDOUT" => "true",
       # name change here because only OOD_* from apache is allowed through sudo rules
       "ALLOWED_HOSTS" => ENV['OOD_ALLOWED_HOSTS'],
+      # set the duplicate to keep clean_nginx_env impepodent
```
Comment (Oglopf) [inline nginx_stage/lib/nginx_stage.rb:148]: I can't seem to add the change myself, but should that read idempotent? (hard to say and spell).
