### PR TITLE
Bug fix/sanitize manifest

### LINKED ISSUE #1969: manifest needs to sanitize itself
manifest will accept and write anything. This behavior shouldn't happen.

`@manifest_options` here, should not have anything that Manifest the class does not respond to.
https://github.com/OSC/ondemand/blob/09923b7a18ba62cdde9078d70fb3ebe509bef033/apps/dashboard/app/apps/manifest.rb#L67

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202169134733195) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by Oglopf**
Fixes #1969

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202257179595965) by [Unito](https://www.unito.io)

### CODE REVIEW

File: apps/dashboard/app/apps/manifest.rb [hunk 1]
```diff
@@ -61,10 +61,13 @@ def self.load_from_string(yaml)
   # @option opts [String] :role Dashboard categorization
   # @option opts [String] :url An optional redirect URL
   # @option opts [Hash]   :metadata An optional hash of key value pairs
+  attr_reader :name, :description
   def initialize(opts)
     raise InvalidContentError.new unless(opts && opts.respond_to?(:to_h))
 
     @manifest_options = opts.to_h.with_indifferent_access
+    #@name = opts[:name]
+    #@description = opts[:description]
```
Comment (johrstrom) [inline apps/dashboard/app/apps/manifest.rb:70]: That reject should probably be here. Seems like it would cover merge and maybe load code paths?

Also be sure to remove that `attr_reader` above.

Comment (Oglopf) [reply apps/dashboard/app/apps/manifest.rb:70]: Bah, can't believe I left that there. Yeah I'll yank it and move the reject up here and yank the sanitze_manifest from save.

File: apps/dashboard/app/apps/manifest.rb [hunk 2]
```diff
@@ -65,6 +65,8 @@ def initialize(opts)
     raise InvalidContentError.new unless(opts && opts.respond_to?(:to_h))
 
     @manifest_options = opts.to_h.with_indifferent_access
+
+    @manifest_options.reject! { |method| !self.respond_to?(method) }
```
Comment (johrstrom) [inline apps/dashboard/app/apps/manifest.rb:69]: does select read better here than reject not?
```suggestion
    @manifest_options = opts.to_h.select do |method| 
       self.respond_to?(method.to_sym)
     end.with_indifferent_access
```

File: apps/dashboard/test/models/manifest_test.rb [hunk 3]
```diff
@@ -126,4 +126,43 @@ class ManifestTest < ActiveSupport::TestCase
...
+    HEREDOC
+
+    manifest = Manifest.new(opts)
+
+    Dir.mktmpdir do |dir|
+      path = dir << '/manifest.yml'
+      manifest.save(path)
+
+      assert_equal valid_manifest, File.read(path)
+    end
```
Comment (johrstrom) [inline apps/dashboard/test/models/manifest_test.rb:166]: Does this work too? (needs some imports probably?). I looked up where this was tripping us up and it's this object type that's being passed. duck type testing may be fine, but I don't know, it's cheap to add the check,

```suggestion
      assert_equal valid_manifest, File.read(path)
      
      manifest = Manifest.new(ActionController::Paramaters.new(param: "shouldn't write me").merge(opts))
      manifest.save(path)
      assert_equal valid_manifest, File.read(path)
    end
```

File: apps/dashboard/app/apps/manifest.rb (hunk 2 above)
Comment (Oglopf) [reply apps/dashboard/app/apps/manifest.rb:69]: Agreed that reads much cleaner and makes sense to chain the `with_indifferent_access` to the end here.

Comment (Oglopf) [reply apps/dashboard/app/apps/manifest.rb:69]: Trying to use `with_indifferent_access` chained on the end causes errors for almost all the test cases with a message of `NoMethodError: undefined method `with_indifferent_access' for nil:NilClass` but keeping it on the original `to_h` results in everything passing with the `select!` method. 

Why does that failure happen? Because if no changes are made, then the `select!` will simply return `nil` which is what is causing the failures https://ruby-doc.org/core-2.7.2/Hash.html#method-i-select-21

So we are a bit stuck having that `with_indifferent_access` on the original `to_h` I believe.

Comment (johrstrom) [reply apps/dashboard/app/apps/manifest.rb:69]: Got it. I'll update the comment with what may work.

File: apps/dashboard/test/models/manifest_test.rb (hunk 3 above)
Comment (Oglopf) [reply apps/dashboard/test/models/manifest_test.rb:166]: It throws an error before ever getting to the `save` in the test. The error that comes up is `ActionController::UnfilteredParameters: unable to convert unpermitted parameters to hash` which seems to be coming from enforcing strong parameters.

But I'm not sure where those strong parameters are defined which it would like. Even passing just a hash that has all the expected fields causes  the error to come up.

Comment (johrstrom) [reply apps/dashboard/test/models/manifest_test.rb:166]: it's fine if it ends up being too hard to test.

File: apps/dashboard/app/apps/manifest.rb (hunk 2 above)
Comment (Oglopf) [reply apps/dashboard/app/apps/manifest.rb:69]: Yeah, that link was to the `select!` method which I was using (noticed the `select` wasn't what we wanted before). 

It notes `keep_if` is an alias for `select!`. Either way even using `select!` causes the behavior as it will still return a `nil` if nothing does change.

File: apps/dashboard/app/apps/manifest.rb [hunk 4]
```diff
@@ -65,6 +65,10 @@ def initialize(opts)
     raise InvalidContentError.new unless(opts && opts.respond_to?(:to_h))
 
     @manifest_options = opts.to_h.with_indifferent_access
+
+    @manifest_options.select! do |method|
```
Comment (johrstrom) [inline apps/dashboard/app/apps/manifest.rb:69]: Why not continue to chain? mutating a member variable a second time seems like a code smell for Ruby.

```suggestion
    @manifest_options = opts.to_h.with_indifferent_access.select! do |method| 
```

Comment (johrstrom) [inline apps/dashboard/app/apps/manifest.rb:69]: Why not continue to chain? mutating a member variable a second time seems like a code smell for Ruby.

```suggestion
    @manifest_options = opts.to_h.with_indifferent_access.select! do |method| 
```

Comment (johrstrom) [reply apps/dashboard/app/apps/manifest.rb:69]: Also I think you want the second parameter there, `_val`. Looping through a single variable means you're looping through keys and values pairs. 

```irb
irb(main):004:0> {a: 'bar'}.each { |p| puts p.inspect }
[:a, "bar"]
```

I'm actually not sure how this works with only 1 parameter to the block.
```irb
irb(main):003:0> {a: 'bar', to_s: 'foo' }.each { |m, val| puts self.respond_to?(m) }
false
true
=> {:a=>"bar", :to_s=>"foo"}
irb(main):004:0> {a: 'bar', to_s: 'foo' }.each { |m| puts self.respond_to?(m) }
Traceback (most recent call last):
        7: from /home/jeff/apps/ruby/2.7.6/bin/irb:23:in `<main>'
        6: from /home/jeff/apps/ruby/2.7.6/bin/irb:23:in `load'
        5: from /home/jeff/apps/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from (irb):4:in `each'
        2: from (irb):4:in `block in irb_binding'
        1: from (irb):4:in `respond_to?'
TypeError ([:a, "bar"] is not a symbol nor a string)


irb(main):003:0> {a: 'bar', to_s: 'foo' }.each { |m, val| puts self.respond_to?(m) }
false
true
```

Comment (johrstrom) [reply apps/dashboard/app/apps/manifest.rb:69]: Also I think you want the second parameter there, `_val`. Looping through a single variable means you're looping through keys and values pairs. 

```irb
irb(main):004:0> {a: 'bar'}.each { |p| puts p.inspect }
[:a, "bar"]
```

I'm actually not sure how this works with only 1 parameter to the block.
```irb
irb(main):003:0> {a: 'bar', to_s: 'foo' }.each { |m, val| puts self.respond_to?(m) }
false
true
=> {:a=>"bar", :to_s=>"foo"}
irb(main):004:0> {a: 'bar', to_s: 'foo' }.each { |m| puts self.respond_to?(m) }
Traceback (most recent call last):
        7: from /home/jeff/apps/ruby/2.7.6/bin/irb:23:in `<main>'
        6: from /home/jeff/apps/ruby/2.7.6/bin/irb:23:in `load'
        5: from /home/jeff/apps/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):4
        3: from (irb):4:in `each'
        2: from (irb):4:in `block in irb_binding'
        1: from (irb):4:in `respond_to?'
TypeError ([:a, "bar"] is not a symbol nor a string)


irb(main):003:0> {a: 'bar', to_s: 'foo' }.each { |m, val| puts self.respond_to?(m) }
false
true
```

**Review by johrstrom — APPROVED** [review]
LGTM
