### PR TITLE
Improved form fixed field UI for new Job Composer scripts

### LINKED ISSUE #3097: fixing a select option should remove all the others.

### PR DESCRIPTION
**Pull request by abujeda**
Fixes #3097 

Improvements to the way select field options are managed when the fixed property is selected.

### CODE REVIEW

**Comment by abujeda** [comment]
This is a demo of the behaviour:

fixed_fields

**Comment by abujeda** [comment]
Reviewing the tests....

**Comment by abujeda** [comment]
Fixed tests

**Comment by johrstrom** [comment]
> Fixed tests

Thanks, I haven't gotten a chance to look this over yet because something came up with my house so I'm on vacation today.  But I'll be sure to sort this out next week.

File: apps/dashboard/app/javascript/script_edit.js [hunk 1]
```diff
@@ -148,38 +148,82 @@ function addInProgressField(event) {
   enableNewFieldButton();
 }
 
+function fixExcludeBasedOnSelect(selectElement) {
+  const excludeElementId = selectElement.dataset.excludeId;
```
Comment (johrstrom) [inline apps/dashboard/app/javascript/script_edit.js:152]: I see this optimization of removing the `target-id` and using this `exclude-id`. 

But it now seems we can take that further and just use `${selectElement.id}_exclude` without having to embed the `data-exlclude-id` at all?

File: apps/dashboard/app/javascript/script_edit.js [hunk 2]
```diff
@@ -148,38 +148,82 @@ function addInProgressField(event) {
...
+}
+
 function fixedFieldEnabled(checkbox, dataElement) {
   // Disable the element to avoid updates from the user
   dataElement.disabled = true;
   // As it is disabled, need to add a hidden field with the same name to send the fixed field value to the backend.
   const input = $('<input>').attr('type','hidden').attr('name', dataElement.name).attr('value', dataElement.value);
   $(checkbox).after(input);
+
+  if (dataElement.nodeName == 'SELECT') {
```
Comment (johrstrom) [inline apps/dashboard/app/javascript/script_edit.js:166]: I cannot find a better way to do this - but I'm calling it out as a `stringly typed language` code smell for me.

That said - I don't think there's anything to do though...

File: apps/dashboard/app/javascript/script_edit.js [hunk 3]
```diff
@@ -148,38 +148,82 @@ function addInProgressField(event) {
...
+    if (dataElement.nodeName == 'SELECT') {
+      fixExcludeBasedOnSelect(dataElement);
+      initSelect(dataElement);
+    }
   }
 
   event.target.disabled = false;
 }
 
+function disableSelectOptionConfig(liElement, addButtonDisabled = false) {
```
Comment (johrstrom) [inline apps/dashboard/app/javascript/script_edit.js:202]: The fact that these methods have a boolean to their interface is a code smell to me.  I know why you have it like that, but I would ask if there's some other way to do this without the second boolean argument.

Comment (johrstrom) [reply apps/dashboard/app/javascript/script_edit.js:202]: At a minimum, it should likely change names to `disableBothButtons` or similar. 

Both of these function always disable at least 1 button and something like `addButtonDisabled` does accurately describe what it does, but that's sort of after you realize/know that `disableSelectOptionConfig` _always_ disables the remove button and this flag is for the other button.

In any case, I think the name change makes it simpler: both these disable _a_ button, with the option to disable both without having to think hard about which one is doing what.

Comment (johrstrom) [reply apps/dashboard/app/javascript/script_edit.js:202]: I think this is my only sticking point with this PR. I would ask if you can see if there's a way to do it without booleans in interfaces.

If not, then that's OK and we can live with it, but I'd like to at least investigate an alternative at any rate..

File: apps/dashboard/app/javascript/script_edit.js (hunk 1 above)
Comment (abujeda) [reply apps/dashboard/app/javascript/script_edit.js:152]: I prefer it explicit in the template. It shows that is is important and is used for something else.
But happy to remove it and use the implicit id by using the format as you describe it.

Let me know if you prefer the optimization.

File: apps/dashboard/app/javascript/script_edit.js (hunk 2 above)
Comment (abujeda) [reply apps/dashboard/app/javascript/script_edit.js:166]: I can add a flag into the fixed checkbox input in the template when it is used for a select field. And change the JS to check for that flag instead.

```js
if (dataElement.dataset.select) {
...
```

File: apps/dashboard/app/javascript/script_edit.js (hunk 3 above)
Comment (abujeda) [reply apps/dashboard/app/javascript/script_edit.js:202]: I have updated with other solution. Let me know what you think.

File: apps/dashboard/app/javascript/script_edit.js (hunk 1 above)
Comment (johrstrom) [reply apps/dashboard/app/javascript/script_edit.js:152]: >I prefer it explicit in the template. It shows that is is important and is used for something else.

If you have this preference, that's fine we can keep it as is.

File: apps/dashboard/app/javascript/script_edit.js (hunk 3 above)
Comment (johrstrom) [reply apps/dashboard/app/javascript/script_edit.js]: I'm going to apologize for this upfront: I think the first solution is better. I know I kind of asked for the impossible - but at least the first solution had modifications co-located to each other and I would guess that's easier to reason about.

How about we go back to the original implementation with a name change. I'd guess that's the best we can do.

File: apps/dashboard/app/javascript/script_edit.js (hunk 2 above)
Comment (johrstrom) [reply apps/dashboard/app/javascript/script_edit.js:166]: I would have to check if this errors, but if it's safe then yes this is preferable. But again, it's got to be safe - so I'd have to check on that.

File: apps/dashboard/app/javascript/script_edit.js (hunk 3 above)
Comment (abujeda) [reply apps/dashboard/app/javascript/script_edit.js]: OK - will do

Comment (abujeda) [reply apps/dashboard/app/javascript/script_edit.js]: I settle for the new names: `enableAddOption`, `enableRemoveOption`.
The name `disableBothButtons` didn't quite represent what the function was doing and there is the other function that does the opposite. Although both functions need to disable buttons.

What do you think about the new names?
Other suggestions for both methods?

**Review by johrstrom — APPROVED** [review]
Works for me!

File: apps/dashboard/app/javascript/script_edit.js (hunk 2 above)
Comment (johrstrom) [reply apps/dashboard/app/javascript/script_edit.js:166]: I know we merged this as is, but while it's on my mind, I found a similar need in another feature. 

HTMLInputElement types have `type` API that I think we should use. I think this because a checkboxes `nodeName` and `tagName` both return `INPUT` where the `type` returns `checkbox`.  Similar thing with text inputs.

Just FYI.
