### PR TITLE
hide download buttons for certain files

### LINKED ISSUE #3029: Files app: downloading a FIFO file fails silently
How to reproduce:

- In your home folder, or wherever you can go with the OOD Files app, create a FIFO file: `mkfifo ood-reproducer`
- Write something into the FIFO: `date > ood-reproducer`
  - Note that this command will block, but that's expected.
- Via a browser with OOD, find the `ood-reproducer` file and try to download it

Expected results:
- There should be some kind of error notification that I could not download the file

Actual results:
- Nothing is shown to the user.
- There is a HTTP request for `<path to files app>/fs/<path to fifo>/ood-reproducer?download=<millisecond timestamp>` which returns `HTTP 200` that contains a HTML render with an error notification, but none of that shown to me in Firefox 116, nor Chromium 116.

This issue touches on #3026, but is more focused on actually conveying error messages, rather than preventing misunderstandings.

### PR DESCRIPTION
**Pull request by johrstrom**
Fixes #3029 by not showing download buttons for things that are not downloadable (i.e., files that are not readable or pipes).

In draft while I write a test case.

### CODE REVIEW

File: apps/dashboard/app/models/posix_file.rb [hunk 1]
```diff
@@ -53,15 +53,16 @@ def to_h
...
+      id:           "dev-#{stat.dev}-inode-#{stat.ino}",
+      name:         basename,
+      size:         directory? ? nil : stat.size,
+      human_size:   human_size,
+      directory:    directory?,
+      date:         stat.mtime.to_i,
+      owner:        PosixFile.username_from_cache(stat.uid),
+      mode:         stat.mode,
+      dev:          stat.dev,
+      downloadable: !pipe? && readable?
```
Comment (johrstrom) [inline apps/dashboard/app/models/posix_file.rb:65]: I only just added the `downloadable` field, but had to shift everything over a space or two for linters.

**Comment by johrstrom** [comment]
Note that the download button outside of the table is still available when folks click the row.  We'll have to pick that up in another pull request.

**Review by Oglopf — APPROVED** [review]
Looks good!
