### PR TITLE
Fix gnome desktop

### LINKED ISSUE #2896: support gnome 3 & 4
I can't tell the Gnome version being invoked here, but it seems to be just gnome 2. This ticket is to update this file to support gnome 3 and 4.

https://github.com/OSC/ondemand/blob/master/apps/bc_desktop/template/desktops/gnome.sh

### PR DESCRIPTION
**Pull request by johrstrom**
Fixes #2896 with the additional bonus of fixing gnome on el7 (doesn't work on OSC systems currently).

### CODE REVIEW

File: apps/bc_desktop/template/desktops/gnome.sh [hunk 1]
```diff
@@ -13,5 +13,33 @@ if [[ -f "${HOME}/.config/monitors.xml" ]]; then
...
+
+if [[ "$ID_LIKE" =~ "fedora" ]]; then
+  if [[ "$VERSION_ID" < "8.0" ]]; then
+    # el7 will crash using wayland.
+    classic
+  else
+    wayland
+  fi
+else
+  wayland
```
Comment (johrstrom) [inline apps/bc_desktop/template/desktops/gnome.sh:41]: This block is for debian which I can only assume wayland works for it.

**Review by HazelGrant — APPROVED** [review]
