### PR TITLE
fix flaky file test by resetting the session

### LINKED ISSUE #3492: another flaky test in
#3483 seems to have introduced a bit of flakiness in our tests. 

Tests will occasionally fail with this error message. It seems to indicate that the `path_selector` in the `projects#new` cannot retrieve the files to build the table for the path_selector.

```
Failure:
RemoteFilesTest#test_visiting_files_app_doesn't_raise_js_errors [test/system/remote_files_test.rb:12]:
console error messages include:

2024-04-03 15:35:19 +0000 INFO: http://127.0.0.1:46097/assets/projects_new-44e20e25f0d0581e936c18cfd4b8508ce5f2e79851e875c659a81523dc05baed.js 93:14 TypeError: Failed to fetch

```

### PR DESCRIPTION
**Pull request by johrstrom**
fix flaky file test by resetting the session

Fixes #3492

### CODE REVIEW

File: apps/dashboard/test/system/batch_connect_test.rb [hunk 1]
```diff
@@ -1444,8 +1444,8 @@ def make_bc_app(dir, form)
   def get_favorites
     # For debugging flaky tests
     favorites = all('#favorites li', wait: 30)
-    puts "FAVORITES: "
-    puts favorites.map{|i| i['innerHTML']}.join('')
+    # puts "FAVORITES: "
+    # puts favorites.map{|i| i['innerHTML']}.join('')
```
Comment (johrstrom) [inline apps/dashboard/test/system/batch_connect_test.rb:1448]: This change isn't a part of this really - I just wanted to get rid of this stdout in tests.

**Review by Oglopf — APPROVED** [review]
Looks good.
