### PR TITLE
fix #692 by using #all instead of #preload

### LINKED ISSUE #692: job composer fails with "SQLite3::SQLException: too many SQL variables"
We just got a service now INC where a user has many workflows and recieved `SQLite3::SQLException: too many SQL variables` error. They'll likely have to remove many of their past jobs, but it indicates a larger issue where there's an upper bound on how many jobs a user can have.

```
App 83056 output: rkflow_id\", 283], [\"workflow_id\", 285], [\"workflow_id\", 286], [\"workflow_id\", 295], [\"workflow_id\", 296], [\"workflow_id\", 298], [\"workflow_id\", 299], [\"workflow_id\", 300], [\"workflow_id\", 301], [\"workflow_id\", 303], [\"workflow_id\", 304], [\"workflow_id\", 305], [\"workflow_id\", 306], [\"workflow_id\", 307], [\"workflow_id\", 308], [\"workflow_id\", 309], [\"workflow_id\", 310], [\"workflow_id\", 311], [\"workflow_id\", 312], [\"workflow_id\", 313], [\"workflow_id\", 314], [\"workflow_id\", 315], [\"workflow_id\", 316], [\"workflow_id\", 317], [\"workflow_id\", 318], [\"workflow_id\", 320], [\"workflow_id\", 321], [\"workflow_id\", 322], [\"workflow_id\", 323], [\"workflow_id\", 324], [\"workflow_id\", 325], [\"workflow_id\", 326], [\"workflow_id\", 327], [\"workflow_id\", 328], [\"workflow_id\", 329], [\"workflow_id\", 330], [\"workflow_id\", 331], [\"workflow_id\", 332], [\"workflow_id\", 333], [\"workflow_id\", 335], [\"workflow_id\", 336], [\"workflow_id\", 338], [\"workflow_id\", 339], [\"workflow_id\", 340], [\"workflow_id\", 341], [\"workflow_id\", 342], [\"workflow_id\", 343], [\"workflow_id\", 345], [\"workflow_id\", 346], [\"workflow_id\", 347], [\"workflow_id\", 348], [\"workflow_id\", 349], [\"workflow_id\", 350], [\"workflow_id\", 351], [\"workflow_id\", 352], [\"workflow_id\", 353], [\"workflow_id\", 354], [\"workflow_id\", 355], [\"workflow_id\", 356], [\"workflow_id\", 358], [\"workflow_id\", 359], [\"workflow_id\", 360], [\"workflow_id\", 361], [\"workflow_id\", 365], [\"workflow_id\", 366], [\"workflow_id\", 368], [\"workflow_id\", 370], [\"workflow_id\", 371], [\"workflow_id\", 373], [\"workflow_id\", 379], [\"workflow_id\", 380], [\"workflow_id\", 381], [\"workflow_id\", 382], [\"workflow_id\", 383], [\"workflow_id\", 384], [\"workflow_id\", 385], [\"workflow_id\", 388], [\"workflow_id\", 389], [\"workflow_id\", 390], [\"workflow_id\", 391], [\"workflow_id\", 392], [\"workflow_id\", 393], [\"workflow_id\", 394], [\"workflow_id\", 397], [\"workflow_id\", 398], [\"workflow_id\", 400], [\"workflow_id\", 401], [\"workflow_id\", 402], [\"workflow_id\", 404], [\"workflow_id\", 405], [\"workflow_id\", 406], [\"workflow_id\", 407], [\"workflow_id\", 408], [\"workflow_id\", 409], [\"workflow_id\", 413], [\"workflow_id\", 414], [\"workflow_id\", 415], [\"workflow_id\", 416], [\"workflow_id\", 417], [\"workflow_id\", 418], [\"workflow_id\", 419], [\"workflow_id\", 421], [\"workflow_id\", 422], [\"workflow_id\", 426], [\"workflow_id\", 427], [\"workflow_id\", 428], [\"workflow_id\", 429], [\"workflow_id\", 430], [\"workflow_id\", 431], [\"workflow_id\", 432], [\"workflow_id\", 433], [\"workflow_id\", 434], [\"workflow_id\", 435], [\"workflow_id\", 436], [\"workflow_id\", 437], [\"workflow_id\", 438], [\"workflow_id\", 439], [\"workflow_id\", 440], [\"workflow_id\", 441], [\"workflow_id\", 442], [\"workflow_id\", 443], [\"workflow_id\", 444], [\"workflow_id\", 447], [\"workflow_id\", 449], [\"workflow_id\", 450], [\"workflow_id\", 452], [\"workflow_id\", 453], [\"workflow_id\", 454], [\"workflow_id\", 455], [\"workflow_id\", 456], [\"workflow_id\", 457], [\"workflow_id\", 458], [\"workflow_id\", 459], [\"workflow_id\", 460], [\"workflow_id\", 461], [\"workflow_id\", 462], [\"workflow_id\", 463], [\"workflow_id\", 464], [\"workflow_id\", 465], [\"workflow_id\", 466], [\"workflow_id\", 467], [\"workflow_id\", 468], [\"workflow_id\", 469], [\"workflow_id\", 470], [\"workflow_id\", 471], [\"workflow_id\", 472], [\"workflow_id\", 473], [\"workflow_id\", 474], [\"workflow_id\", 475], [\"workflow_id\", 476], [\"workflow_id\", 477], [\"workflow_id\", 478], [\"workflow_id\", 484], [\"workflow_id\", 485], [\"workflow_id\", 486], [\"workflow_id\", 487], [\"workflow_id\", 488], [\"workflow_id\", 489], [\"workflow_id\", 490], [\"workflow_id\", 491], [\"workflow_id\", 492], [\"workflow_id\", 493], [\"workflow_id\", 494], [\"workflow_id\", 495], [\"workflow_id\", 496], [\"workflow_id\", 497], [\"workflow_id\", 498], [\"workflow_id\", 499], [\"workflow_id\", 500], [\"workflow_id\", 501], [\"workflow_id\", 502], [\"workflow_id\", 503], [\"workflow_id\", 504], [\"workflow_id\", 505], [\"workflow_id\", 506], [\"workflow_id\", 507], [\"workflow_id\", 508], [\"workflow_id\", 509], [\"workflow_id\", 511], [\"workflow_id\", 512], [\"workflow_id\", 513], [\"workflow_id\", 514], [\"workflow_id\", 515], [\"workflow_id\", 516], [\"workflow_id\", 517], [\"workflow_id\", 518], [\"workflow_id\", 519], [\"workflow_id\", 520], [\"workflow_id\", 521], [\"workflow_id\", 522], [\"workflow_id\", 523], [\"workflow_id\", 524], [\"workflow_id\", 525], [\"workflow_id\", 526], [\"workflow_id\", 527], [\"workflow_id\", 528], [\"workflow_id\", 529], [\"workflow_id\", 530], [\"workflow_id\", 531], [\"workflow_id\", 535], [\"workflow_id\", 536], [\"workflow_id\", 537], [\"workflow_id\", 538], [\"workflow_id\", 539], [\"workflow_id\", 540], [\"workflow_id\", 547], [\"workflow_id\", 548], [\"workflow_id\", 549], [\"workflow_id\", 550], [\"workflow_id\", 554], [\"workflow_id\", 555], [\"workflow_id\", 557], [\"workflow_id\", 558], [\"workflow_id\", 559], [\"workflow_id\", 560], [\"workflow_id\", 561], [\"workflow_id\", 562], [\"workflow_id\", 563], [\"workflow_id\", 564], [\"workflow_id\", 566], [\"workflow_id\", 567], [\"workflow_id\", 571], [\"workflow_id\", 572], [\"workflow_id\", 573], [\"workflow_id\", 574], [\"workflow_id\", 575], [\"workflow_id\", 577], [\"workflow_id\", 578], [\"workflow_id\", 579], [\"workflow_id\", 580], [\"workflow_id\", 581], [\"workflow_id\", 582], [\"workflow_id\", 583], [\"workflow_id\", 584], [\"workflow_id\", 586], [\"workflow_id\", 587], [\"workflow_id\", 588], [\"workflow_id\", 590], [\"workflow_id\", 591], [\"workflow_id\", 592], [\"workflow_id\", 593], [\"workflow_id\", 596], [\"workflow_id\", 598], [\"workflow_id\", 600], [\"workflow_id\", 601], [\"workflow_id\", 603], [\"workflow_id\", 604], [\"workflow_id\", 607], [\"workflow_id\", 608], [\"workflow_id\", 609], [\"workflow_id\", 610], [\"workflow_id\", 611], [\"workflow_id\", 612], [\"workflow_id\", 613], [\"workflow_id\", 614], [\"workflow_id\", 616], [\"workflow_id\", 617], [\"workflow_id\", 618], [\"workflow_id\", 665], [\"workflow_id\", 666], [\"workflow_id\", 668], [\"workflow_id\", 669], [\"workflow_id\", 670], [\"workflow_id\", 675], [\"workflow_id\", 686], [\"workflow_id\", 692], [\"workflow_id\", 703], [\"workflow_id\", 704], [\"workflow_id\", 724], [\"workflow_id\", 727], [\"workflow_id\", 728], [\"workflow_id\", 729], [\"workflow_id\", 730], [\"workflow_id\", 731], [\"workflow_id\", 733], [\"workflow_id\", 734], [\"workflow_id\", 735], [\"workflow_id\", 736], [\"workflow_id\", 737], [\"workflow_id\", 738], [\"workflow_id\", 739], [\"workflow_id\", 740], [\"workflow_id\", 741], [\"workflow_id\", 742], [\"workflow_id\", 743], [\"workflow_id\", 753], [\"workflow_id\", 754], [\"workflow_id\", 756], [\"workflow_id\", 757], [\"workflow_id\", 758], [\"workflow_id\", 759], [\"workflow_id\", 760], [\"workflow_id\", 766], [\"workflow_id\", 767], [\"workflow_id\", 768], [\"workflow_id\", 770], [\"workflow_id\", 771], [\"workflow_id\", 773], [\"workflow_id\", 775], [\"workflow_id\", 776], [\"workflow_id\", 777], [\"workflow_id\", 778], [\"workflow_id\", 779], [\"workflow_id\", 780], [\"workflow_id\", 781], [\"workflow_id\", 782], [\"workflow_id\", 783], [\"workflow_id\", 784], [\"workflow_id\", 789], [\"workflow_id\", 790], [\"workflow_id\", 791], [\"workflow_id\", 792], [\"workflow_id\", 793], [\"workflow_id\", 794], [\"workflow_id\", 795], [\"workflow_id\", 796], [\"workflow_id\", 797], [\"workflow_id\", 798], [\"workflow_id\", 799], [\"workflow_id\", 800], [\"workflow_id\", 801], [\"workflow_id\", 802], [\"workflow_id\", 803], [\"workflow_id\", 804], [\"workflow_id\", 805], [\"workflow_id\", 806], [\"workflow_id\", 807], [\"workflow_id\", 808], [\"workflow_id\", 809], [\"workflow_id\", 810], [\"workflow_id\", 811], [\"workflow_id\", 812], [\"workflow_id\", 813], [\"workflow_id\", 815], [\"workflow_id\", 816], [\"workflow_id\", 817], [\"workflow_id\", 818], [\"workflow_id\", 819], [\"workflow_id\", 820], [\"workflow_id\", 825], [\"workflow_id\", 826], [\"workflow_i
App 83056 output: d\", 827], [\"workflow_id\", 828], [\"workflow_id\", 829], [\"workflow_id\", 830], [\"workflow_id\", 832], [\"workflow_id\", 833], [\"workflow_id\", 835], [\"workflow_id\", 836], [\"workflow_id\", 837], [\"workflow_id\", 838], [\"workflow_id\", 839], [\"workflow_id\", 840], [\"workflow_id\", 841], [\"workflow_id\", 842], [\"workflow_id\", 843], [\"workflow_id\", 844], [\"workflow_id\", 845], [\"workflow_id\", 846], [\"workflow_id\", 847], [\"workflow_id\", 848], [\"workflow_id\", 849], [\"workflow_id\", 850], [\"workflow_id\", 851], [\"workflow_id\", 852], [\"workflow_id\", 853], [\"workflow_id\", 854], [\"workflow_id\", 855], [\"workflow_id\", 856], [\"workflow_id\", 857], [\"workflow_id\", 858], [\"workflow_id\", 859], [\"workflow_id\", 860], [\"workflow_id\", 861], [\"workflow_id\", 862], [\"workflow_id\", 863], [\"workflow_id\", 864], [\"workflow_id\", 866], [\"workflow_id\", 867], [\"workflow_id\", 868], [\"workflow_id\", 869], [\"workflow_id\", 871], [\"workflow_id\", 872], [\"workflow_id\", 873], [\"workflow_id\", 874], [\"workflow_id\", 875], [\"workflow_id\", 876], [\"workflow_id\", 877], [\"workflow_id\", 878], [\"workflow_id\", 879], [\"workflow_id\", 880], [\"workflow_id\", 881], [\"workflow_id\", 882], [\"workflow_id\", 883], [\"workflow_id\", 884], [\"workflow_id\", 885], [\"workflow_id\", 886], [\"workflow_id\", 887], [\"workflow_id\", 888], [\"workflow_id\", 889], [\"workflow_id\", 890], [\"workflow_id\", 891], [\"workflow_id\", 892], [\"workflow_id\", 893], [\"workflow_id\", 894], [\"workflow_id\", 895], [\"workflow_id\", 896], [\"workflow_id\", 897], [\"workflow_id\", 899], [\"workflow_id\", 900], [\"workflow_id\", 901], [\"workflow_id\", 902], [\"workflow_id\", 903], [\"workflow_id\", 910], [\"workflow_id\", 911], [\"workflow_id\", 912], [\"workflow_id\", 914], [\"workflow_id\", 915], [\"workflow_id\", 924], [\"workflow_id\", 937], [\"workflow_id\", 939], [\"workflow_id\", 940], [\"workflow_id\", 942], [\"workflow_id\", 943], [\"workflow_id\", 944], [\"workflow_id\", 945], [\"workflow_id\", 948], [\"workflow_id\", 949], [\"workflow_id\", 951], [\"workflow_id\", 952], [\"workflow_id\", 954], [\"workflow_id\", 961], [\"workflow_id\", 962], [\"workflow_id\", 964], [\"workflow_id\", 965], [\"workflow_id\", 966], [\"workflow_id\", 968], [\"workflow_id\", 969], [\"workflow_id\", 971], [\"workflow_id\", 972], [\"workflow_id\", 973], [\"workflow_id\", 975], [\"workflow_id\", 976], [\"workflow_id\", 981], [\"workflow_id\", 982], [\"workflow_id\", 983], [\"workflow_id\", 984], [\"workflow_id\", 986], [\"workflow_id\", 987], [\"workflow_id\", 988], [\"workflow_id\", 989], [\"workflow_id\", 990], [\"workflow_id\", 992], [\"workflow_id\", 993], [\"workflow_id\", 994], [\"workflow_id\", 995], [\"workflow_id\", 996], [\"workflow_id\", 999], [\"workflow_id\", 1000], [\"workflow_id\", 1001], [\"workflow_id\", 1002], [\"workflow_id\", 1018], [\"workflow_id\", 1019], [\"workflow_id\", 1020], [\"workflow_id\", 1021], [\"workflow_id\", 1023], [\"workflow_id\", 1027], [\"workflow_id\", 1028], [\"workflow_id\", 1031], [\"workflow_id\", 1032], [\"workflow_id\", 1033], [\"workflow_id\", 1035], [\"workflow_id\", 1036], [\"workflow_id\", 1037], [\"workflow_id\", 1038], [\"workflow_id\", 1040], [\"workflow_id\", 1043], [\"workflow_id\", 1049], [\"workflow_id\", 1054], [\"workflow_id\", 1056], [\"workflow_id\", 1061], [\"workflow_id\", 1076], [\"workflow_id\", 1095], [\"workflow_id\", 1097], [\"workflow_id\", 1103], [\"workflow_id\", 1104], [\"workflow_id\", 1105], [\"workflow_id\", 1106], [\"workflow_id\", 1107], [\"workflow_id\", 1108], [\"workflow_id\", 1110], [\"workflow_id\", 1111], [\"workflow_id\", 1112], [\"workflow_id\", 1113], [\"workflow_id\", 1114], [\"workflow_id\", 1115], [\"workflow_id\", 1122], [\"workflow_id\", 1128], [\"workflow_id\", 1129], [\"workflow_id\", 1130], [\"workflow_id\", 1131], [\"workflow_id\", 1133], [\"workflow_id\", 1134], [\"workflow_id\", 1135], [\"workflow_id\", 1136], [\"workflow_id\", 1137], [\"workflow_id\", 1138], [\"workflow_id\", 1139], [\"workflow_id\", 1140], [\"workflow_id\", 1141], [\"workflow_id\", 1142], [\"workflow_id\", 1145], [\"workflow_id\", 1155], [\"workflow_id\", 1156], [\"workflow_id\", 1157], [\"workflow_id\", 1158], [\"workflow_id\", 1159], [\"workflow_id\", 1160], [\"workflow_id\", 1171], [\"workflow_id\", 1172], [\"workflow_id\", 1174], [\"workflow_id\", 1175], [\"workflow_id\", 1183], [\"workflow_id\", 1210], [\"workflow_id\", 1211], [\"workflow_id\", 1212], [\"workflow_id\", 1213], [\"workflow_id\", 1214], [\"workflow_id\", 1215], [\"workflow_id\", 1249], [\"workflow_id\", 1256], [\"workflow_id\", 1257], [\"workflow_id\", 1258], [\"workflow_id\", 1259], [\"workflow_id\", 1260], [\"workflow_id\", 1261], [\"workflow_id\", 1266], [\"workflow_id\", 1267], [\"workflow_id\", 1268], [\"workflow_id\", 1271], [\"workflow_id\", 1272], [\"workflow_id\", 1276], [\"workflow_id\", 1279], [\"workflow_id\", 1280], [\"workflow_id\", 1314], [\"workflow_id\", 1316], [\"workflow_id\", 1318], [\"workflow_id\", 1319], [\"workflow_id\", 1339], [\"workflow_id\", 1349], [\"workflow_id\", 1350], [\"workflow_id\", 1351], [\"workflow_id\", 1354], [\"workflow_id\", 1355], [\"workflow_id\", 1356], [\"workflow_id\", 1357], [\"workflow_id\", 1358], [\"workflow_id\", 1359], [\"workflow_id\", 1360], [\"workflow_id\", 1370], [\"workflow_id\", 1371], [\"workflow_id\", 1372], [\"workflow_id\", 1374], [\"workflow_id\", 1375], [\"workflow_id\", 1382], [\"workflow_id\", 1383], [\"workflow_id\", 1385], [\"workflow_id\", 1387], [\"workflow_id\", 1394], [\"workflow_id\", 1395], [\"workflow_id\", 1396], [\"workflow_id\", 1397], [\"workflow_id\", 1398], [\"workflow_id\", 1399], [\"workflow_id\", 1400], [\"workflow_id\", 1401], [\"workflow_id\", 1402], [\"workflow_id\", 1403], [\"workflow_id\", 1404], [\"workflow_id\", 1405], [\"workflow_id\", 1406], [\"workflow_id\", 1407], [\"workflow_id\", 1409], [\"workflow_id\", 1410], [\"workflow_id\", 1411], [\"workflow_id\", 1412], [\"workflow_id\", 1413], [\"workflow_id\", 1414], [\"workflow_id\", 1415], [\"workflow_id\", 1416], [\"workflow_id\", 1417], [\"workflow_id\", 1418], [\"workflow_id\", 1419], [\"workflow_id\", 1420], [\"workflow_id\", 1421], [\"workflow_id\", 1422], [\"workflow_id\", 1423], [\"workflow_id\", 1424], [\"workflow_id\", 1425], [\"workflow_id\", 1426], [\"workflow_id\", 1427], [\"workflow_id\", 1438], [\"workflow_id\", 1439], [\"workflow_id\", 1440], [\"workflow_id\", 1441], [\"workflow_id\", 1442], [\"workflow_id\", 1450], [\"workflow_id\", 1452], [\"workflow_id\", 1469], [\"workflow_id\", 1470], [\"workflow_id\", 1471], [\"workflow_id\", 1472], [\"workflow_id\", 1473], [\"workflow_id\", 1475], [\"workflow_id\", 1477], [\"workflow_id\", 1478], [\"workflow_id\", 1480], [\"workflow_id\", 1481], [\"workflow_id\", 1482], [\"workflow_id\", 1488], [\"workflow_id\", 1489], [\"workflow_id\", 1490], [\"workflow_id\", 1491], [\"workflow_id\", 1494], [\"workflow_id\", 1495], [\"workflow_id\", 1496], [\"workflow_id\", 1497], [\"workflow_id\", 1498], [\"workflow_id\", 1499], [\"workflow_id\", 1504], [\"workflow_id\", 1505], [\"workflow_id\", 1515], [\"workflow_id\", 1518], [\"workflow_id\", 1520], [\"workflow_id\", 1521], [\"workflow_id\", 1522], [\"workflow_id\", 1523], [\"workflow_id\", 1524], [\"workflow_id\", 1525], [\"workflow_id\", 1526], [\"workflow_id\", 1527], [\"workflow_id\", 1528], [\"workflow_id\", 1529], [\"workflow_id\", 1530], [\"workflow_id\", 1531], [\"workflow_id\", 1532], [\"workflow_id\", 1533], [\"workflow_id\", 1536], [\"workflow_id\", 1537], [\"workflow_id\", 1538], [\"workflow_id\", 1539], [\"workflow_id\", 1540], [\"workflow_id\", 1541], [\"workflow_id\", 1542], [\"workflow_id\", 1543], [\"workflow_id\", 1544], [\"workflow_id\", 1545], [\"workflow_id\", 1546], [\"workflow_id\", 1547], [\"workflow_id\", 1549], [\"workflow_id\", 1550], [\"workflow_id\", 1551], [\"workflow_id\", 1552], [\"workflow_id\", 1553], [\"workflow_id\", 1554], [\"workflow_id\", 1555], [\"workflow_id\", 1556], [\"workflow_id\", 1557], [\"workflow_id\", 1558], [\"workflow_id\", 1559], [\"workflow_id\", 1560], [\"workflow_id\", 1561], [\"workflow_id\", 1562], [\"workflow_id\", 1564
App 83056 output: ], [\"workflow_id\", 1568], [\"workflow_id\", 1569], [\"workflow_id\", 1570], [\"workflow_id\", 1571], [\"workflow_id\", 1572], [\"workflow_id\", 1573], [\"workflow_id\", 1574], [\"workflow_id\", 1575], [\"workflow_id\", 1576], [\"workflow_id\", 1577], [\"workflow_id\", 1579], [\"workflow_id\", 1580], [\"workflow_id\", 1581], [\"workflow_id\", 1582], [\"workflow_id\", 1585], [\"workflow_id\", 1586], [\"workflow_id\", 1588], [\"workflow_id\", 1589], [\"workflow_id\", 1590], [\"workflow_id\", 1591], [\"workflow_id\", 1592], [\"workflow_id\", 1593], [\"workflow_id\", 1595], [\"workflow_id\", 1596], [\"workflow_id\", 1597], [\"workflow_id\", 1598], [\"workflow_id\", 1599], [\"workflow_id\", 1600], [\"workflow_id\", 1601], [\"workflow_id\", 1602], [\"workflow_id\", 1603], [\"workflow_id\", 1604], [\"workflow_id\", 1605], [\"workflow_id\", 1606], [\"workflow_id\", 1607], [\"workflow_id\", 1608], [\"workflow_id\", 1609], [\"workflow_id\", 1610], [\"workflow_id\", 1611], [\"workflow_id\", 1612], [\"workflow_id\", 1613], [\"workflow_id\", 1614], [\"workflow_id\", 1615], [\"workflow_id\", 1616], [\"workflow_id\", 1617], [\"workflow_id\", 1618], [\"workflow_id\", 1619], [\"workflow_id\", 1621], [\"workflow_id\", 1622], [\"workflow_id\", 1623], [\"workflow_id\", 1624], [\"workflow_id\", 1625], [\"workflow_id\", 1627], [\"workflow_id\", 1628], [\"workflow_id\", 1629], [\"workflow_id\", 1630], [\"workflow_id\", 1631], [\"workflow_id\", 1634], [\"workflow_id\", 1635], [\"workflow_id\", 1637], [\"workflow_id\", 1638], [\"workflow_id\", 1639], [\"workflow_id\", 1640], [\"workflow_id\", 1642], [\"workflow_id\", 1643], [\"workflow_id\", 1644], [\"workflow_id\", 1645], [\"workflow_id\", 1646], [\"workflow_id\", 1647], [\"workflow_id\", 1648], [\"workflow_id\", 1650], [\"workflow_id\", 1652], [\"workflow_id\", 1653], [\"workflow_id\", 1655], [\"workflow_id\", 1656], [\"workflow_id\", 1657], [\"workflow_id\", 1658], [\"workflow_id\", 1659], [\"workflow_id\", 1660], [\"workflow_id\", 1661], [\"workflow_id\", 1662], [\"workflow_id\", 1663], [\"workflow_id\", 1664], [\"workflow_id\", 1665], [\"workflow_id\", 1666], [\"workflow_id\", 1671], [\"workflow_id\", 1672], [\"workflow_id\", 1673], [\"workflow_id\", 1674], [\"workflow_id\", 1675], [\"workflow_id\", 1676], [\"workflow_id\", 1677], [\"workflow_id\", 1678], [\"workflow_id\", 1679], [\"workflow_id\", 1681], [\"workflow_id\", 1682], [\"workflow_id\", 1683], [\"workflow_id\", 1684], [\"workflow_id\", 1685], [\"workflow_id\", 1686], [\"workflow_id\", 1687], [\"workflow_id\", 1688], [\"workflow_id\", 1689], [\"workflow_id\", 1690], [\"workflow_id\", 1691], [\"workflow_id\", 1692], [\"workflow_id\", 1693], [\"workflow_id\", 1694], [\"workflow_id\", 1695], [\"workflow_id\", 1696], [\"workflow_id\", 1697], [\"workflow_id\", 1698], [\"workflow_id\", 1699], [\"workflow_id\", 1700]]"
App 83056 output: [2020-10-04 10:55:56 -0400 ]  INFO "method=GET path=/pun/sys/myjobs/ format=html controller=WorkflowsController action=index status=500 error='ActionView::Template::Error: SQLite3::SQLException: too many SQL variables: SELECT \"jobs\".* FROM \"jobs\" WHERE \"jobs\".\"workflow_id\" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' duration=198.82 view=0.00 db=35.66"
App 83056 output: [2020-10-04 10:55:56 -0400 ] FATAL ""
App 83056 output: [2020-10-04 10:55:56 -0400 ] FATAL "ActionView::Template::Error (SQLite3::SQLException: too many SQL variables: SELECT \"jobs\".* FROM \"jobs\" WHERE \"jobs\".\"workflow_id\" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)):"
App 83056 output: [2020-10-04 10:55:56 -0400 ] FATAL "78:           </thead>\n    79: \n    80:           <tbody>\n    81:           <% @workflows.each do |workflow| %>\n    82:               <tr class=\"job-row<%= \" missing-cluster\" unless workflow.batch_host_exists? %><%= \" missing-dir\" unless workflow.staged_dir_exists? %><%= \" missing-script\" unless workflow.script_name && workflow.staged_script_exists? %>\" id=\"<%= workflow.id %>\">\n    83:                 <td data-sort=\"<%= workflow.id %>\"><small><%= local_time(workflow.created_at) %></small></td>\n    84:                 <td><span title=\"<%= workflow.name %>\"><strong><%= workflow.name %></strong></span></td>"
App 83056 output: [2020-10-04 10:55:56 -0400 ] FATAL ""
```

### PR DESCRIPTION
**Pull request by johrstrom**
Fixes #692 

ActiveRecord#preload uses a 'where in ...' clause and sqlite3 has limitations of 1000 variables in that 'in' portion. So just get all
workflows.

### CODE REVIEW

File: apps/myjobs/app/controllers/workflows_controller.rb [hunk 1]
```diff
@@ -13,7 +13,7 @@ def index
 
     @selected_id = session[:selected_id]
     session[:selected_id] = nil
-    @workflows = Workflow.preload(:jobs)
+    @workflows = Workflow.all
```
Comment (ericfranz) [inline apps/myjobs/app/controllers/workflows_controller.rb:16]: Problem here is then we introduce an n+1 query problem. 1 query to get all the workflow objects, and then when we iterate over each workflow object to get job status information, we execute one query for each job.

The ideal solution would be to implement pagination, when we are only every querying a subset, and then to preserve the job records of each job submitted.

The current implementation enforces a 1:1 workflow to job record.  In this case though, we only have a 1:1 workflow+job and we might be able to get by using `Workflow.eager_load(:jobs)` instead.

So we need to investigate another solution to just dropping preload.

Comment (johrstrom) [reply apps/myjobs/app/controllers/workflows_controller.rb]: I'm able to confirm that `Workflow.eager_load(:jobs)` works as well. It loads all 1000 records and their associated job if it exists.
