### PR TITLE
rescue chown in case it fails

### LINKED ISSUE #3851: chown can fail in upload
From discourse - https://discourse.openondemand.org/t/file-upload-and-posix-acl-support-updated/3783/2 

apparently when a directory has certain bits set, an upload can fail.

### PR DESCRIPTION
**Pull request by johrstrom**
Fix #3851 by rescing this chown operation in case it fails.

### CODE REVIEW

File: apps/dashboard/app/models/posix_file.rb [hunk 1]
```diff
@@ -151,7 +151,13 @@ def handle_upload(tempfile)
...
     File.chmod(mode, path.to_s)
 
-    path.chown(nil, path.parent.stat.gid) if path.parent.setgid?
+    begin
+      path.chown(nil, path.parent.stat.gid) if path.parent.setgid?
+    rescue StandardError => e
+      Rails.logger.info("cannot chown #{path} because of error: #{e}")
+    end
+
+    nil
```
Comment (johrstrom) [inline apps/dashboard/app/models/posix_file.rb:160]: I'm also ensuring we return nil here because other handle_upload methods return a Transfer.
