### PR TITLE
fix cache key for path selector

### LINKED ISSUE #3246: path selector key corruption
I don't quite know how I got into this state - but my cache key has somehow become corrupted rendering the path selector unusable

It is currently this string - 
"/fs/scratch/PAS1604/results/owens-quick/27598979/phylogatr-results.zip/phylogatr-results.zip/phylogatr-results.zip/phylogatr-results.zip/phylogatr-results.zip/phylogatr-results.zip/phylogatr-results.zip" 

You can see that `phylogatr-results.zip` has been appended to the full path 7 erroneous times somehow.

### PR DESCRIPTION
**Pull request by johrstrom**
This fixes #3246. Added the test case first just to demonstrate that the current code fails this test.

### CODE REVIEW

File: apps/dashboard/app/javascript/path_selector/path_selector_data_table.js [hunk 1]
```diff
@@ -161,7 +160,8 @@ export class PathSelectorTable {
   }
 
   storageKey() {
-    return `${this.tableId}_last_visited`;
+    const underscore_path = window.location.pathname.replaceAll('/', '_');
+    return `${this.tableId}${underscore_path}_last_visited`;
```
Comment (johrstrom) [inline apps/dashboard/app/javascript/path_selector/path_selector_data_table.js:164]: This doesn't actually fix this issue - but it can help with uniqueness in that folks can reuse the same name in multiple forms. So this ensures the cache key is unique to that form.

**Review by HazelGrant — APPROVED** [review]
