### PR TITLE
Fix files preview. Set charset=utf-8 in Content-Type header

### LINKED ISSUE #1218: non-utf8 files don't view correctly
non-utf8 seem to show currpted values when showing in the file viewer. Here's an image of this issue.  One can see that the file editor renders these characters well, where the file viewer does not.

image

Here's the text to replicate this in full.

```text
echo 'hello world!?!?!'

#the calculation = 0.12397 × 1140−8 to 1.556736 × another thing
```

### PR DESCRIPTION
**Pull request by msquee**
Closes #1218.

### CODE REVIEW

File: apps/dashboard/app/models/files.rb [hunk 1]
```diff
@@ -134,7 +134,7 @@ def self.mime_type_for_preview(type)
     #
     case type
     when 'text/javascript', 'text/css', 'text/yaml', 'text/yml'
-      'text/plain'
+      'text/plain; charset=utf-8'
     else
       type
     end
```
Comment (johrstrom) [inline apps/dashboard/app/models/files.rb:140]: I wonder if this can just be text content type?  In any case, in this case I was looking at a shell script that was `text/plain`, which would need to be added to this when block. But what about `text/json`? What about `text/xml` and on and on and on. 

Is there some reason we can't just cast all text formats to `text/plain`?

```ruby
    if %r{text/.*}.match(type).nil?
      type
    else
      'text/plain; charset=utf-8'
    end
```

**Review by johrstrom — APPROVED** [review]
LGTM
