### PR TITLE
3666 disable dl btn when non dlable is checked files

### LINKED ISSUE #3666: disable download button for certain files
Now that we have #3654 - we additionally need to disable the download button when certain files are checked. That is, when a file that is not downloadable (row in the table) is checked we should disable the download button. Otherwise it'll silently fail.

### PR DESCRIPTION
**Pull request by HazelGrant**
Fixes #3666 

https://github.com/user-attachments/assets/e54d8230-dd9f-405b-91cf-ca8115acb125

### CODE REVIEW

File: apps/dashboard/app/javascript/files/data_table.js [hunk 1]
```diff
@@ -222,6 +222,9 @@ class DataTable {
                     data: null,
                     orderable: false,
                     defaultContent: '<input type="checkbox">',
+                    render: (data, type, row, meta) => {
+                        return "<input type='checkbox' data-dl-url='" + row.download_url + "'>";
```
Comment (johrstrom) [inline apps/dashboard/app/javascript/files/data_table.js:226]: Can we use string interpolation here instead? I tend to get turned around by all the quotations in `+` expressions.

```javascript
return `<input type='checkbox' data-dl-url='${row.download_url}'>`;
```

**Review by johrstrom — APPROVED** [review]
LGTM. Thanks for the video demo!
