### PR TITLE
Fix files/api/v1 route not working

### LINKED ISSUE #2239: Files app files/api/v1 route not working in nightly
The old `files/api/v1/` route provided for backwards compatibility seem to not work in nightly as `api` is parsed as parameter `fs` instead.

Should be a simple fix by adding `api` to the `fs` constraint to make it work the same way as `files/edit`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202806703886096) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by robinkar**
Fixes #2239 by adding `api/v1` to the constraints of `fs`, so that `files/api/v1/...` URL is handled in the correct place.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202807937528109) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by johrstrom** [comment]
I need a second to look this over because I'm wondering why tests pass now in mainline without the change. Looking over #2186 it still works but I guess something got broken in between?

File: apps/dashboard/config/routes.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@
 
   # in production, if the user doesn't have access to the files app directory, we hide the routes
   if Configuration.can_access_files?
-    constraints filepath: /.+/, fs: /(?!edit)[^\/]+/  do
+    constraints filepath: /.+/, fs: /(?!(edit|api\/v1))[^\/]+/  do
```
Comment (johrstrom) [inline apps/dashboard/config/routes.rb:14]: I can't replicate on `2.1.20220816-126472.e370f64.nightly`.

Comment (johrstrom) [reply apps/dashboard/config/routes.rb:14]: Though I only spot checked `fs` browsing.

**Comment by johrstrom** [comment]
I see what's going on here. I thought we used the api in the files app - but I guess not. That's why there's no issue - we're not using the thing that's broken!

**Review by johrstrom — APPROVED** [review]
Thanks!
